# SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
# SPDX-License-Identifier: MIT

[Container]

# VOLUMES
Volume=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/root_ca/root_ca.crt:ro,z
Volume=acme-certs.volume:/acme.sh:z

# NETWORKS
Network=openchami-cert-internal.network
PodmanArgs=--http-proxy=false
