# SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
# SPDX-License-Identifier: MIT

[Container]

# VOLUMES
Volume=haproxy-certs.volume:/etc/haproxy/certs/:z

# The haproxy deploy hook requires the target directory in an environment
# variable.
Environment=DEPLOY_HAPROXY_PEM_PATH=/etc/haproxy/certs
